CREATE TABLE IF NOT EXISTS entries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  message TEXT NOT NULL,
  score INTEGER NOT NULL DEFAULT 0,
  run INTEGER NOT NULL DEFAULT 1,
  cleared_runs INTEGER NOT NULL DEFAULT 0,
  stars INTEGER NOT NULL DEFAULT 0,
  lives INTEGER NOT NULL DEFAULT 0,
  result TEXT NOT NULL DEFAULT 'In orbit',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_entries_rank
ON entries (score DESC, cleared_runs DESC, stars DESC, created_at DESC);
